// Copyright 2024 IOTA Stiftung.
// SPDX-License-Identifier: Apache-2.0.
import { ErrorHelper, Is } from "@twin.org/core";
import type { EntityCondition } from "@twin.org/entity";
import type { IRightsManagementPolicy } from "@twin.org/rights-management-models";
import { PolicyAdministrationPointRestClient } from "@twin.org/rights-management-rest-client";

let rightsManagementPapClient: PolicyAdministrationPointRestClient | undefined;

/**
 * Initialise the rights management PAP client.
 * @param apiUrl The API url.
 */
export async function init(apiUrl: string): Promise<void> {
	rightsManagementPapClient = new PolicyAdministrationPointRestClient({
		endpoint: apiUrl
	});
}

/**
 * Get a policy.
 * @param proofId The id of the policy.
 * @returns The policy or an error if one occurred.
 */
export async function policyGet(proofId: string): Promise<
	| {
			error?: string;
			item?: IRightsManagementPolicy;
	  }
	| undefined
> {
	if (Is.object(rightsManagementPapClient)) {
		try {
			const result = await rightsManagementPapClient.get(proofId);
			return {
				item: result
			};
		} catch (err) {
			return {
				error: ErrorHelper.formatErrors(err).join("\n")
			};
		}
	}
}

/**
 * Create a new policy.
 * @param policyObject The policy object to create, it comes without the uid since that will be generated by the server.
 * @returns The id of the created policy or an error if one occurred.
 */
export async function policyCreate(policyObject: IRightsManagementPolicy): Promise<
	| {
			error?: string;
			uid?: string;
	  }
	| undefined
> {
	if (Is.object(rightsManagementPapClient)) {
		try {
			const result = await rightsManagementPapClient.create(policyObject);

			return { uid: result };
		} catch (err) {
			return {
				error: ErrorHelper.formatErrors(err).join("\n")
			};
		}
	}
}

/**
 * Update a policy.
 * @param policyObject The policy object to create.
 * @returns The id of the created policy or an error if one occurred.
 */
export async function policyUpdate(policyObject: IRightsManagementPolicy): Promise<
	| {
			error?: string;
	  }
	| undefined
> {
	if (Is.object(rightsManagementPapClient)) {
		try {
			await rightsManagementPapClient.update(policyObject);
			return undefined;
		} catch (err) {
			return {
				error: ErrorHelper.formatErrors(err).join("\n")
			};
		}
	}
}

/**
 * Remove a Policy.
 * @param policyId The id of the policy to remove.
 * @returns Nothing or an error if one occurred.
 */
export async function policyRemove(policyId: string): Promise<undefined | { error: string }> {
	if (Is.object(rightsManagementPapClient)) {
		try {
			await rightsManagementPapClient.remove(policyId);
			return undefined;
		} catch (err) {
			return {
				error: ErrorHelper.formatErrors(err).join("\n")
			};
		}
	}
}

/**
 * Query policies with optional conditions and pagination.
 * @param conditions The conditions for filtering policies.
 * @param cursor The cursor for pagination.
 * @param limit Limit the number of items for pagination.
 * @returns Nothing or an error if one occurred.
 */
export async function policyQuery(
	conditions?: EntityCondition<IRightsManagementPolicy>,
	cursor?: string,
	limit?: number
): Promise<undefined | { error?: string; cursor?: string; policies?: IRightsManagementPolicy[] }> {
	if (Is.object(rightsManagementPapClient)) {
		try {
			const result = await rightsManagementPapClient.query(undefined, conditions, cursor, limit);
			return {
				cursor: result.cursor,
				policies: result.policies
			};
		} catch (err) {
			return {
				error: ErrorHelper.formatErrors(err).join("\n")
			};
		}
	}
}
